allowBuilds:
  epoll: set this to true or false
  es5-ext: set this to true or false
  esbuild: true
  ffi-napi: set this to true or false
  koffi: set this to true or false
  ref-napi: set this to true or false
